del *.aux /s
del *.bak /s
del *.log /s
del *.bbl /s
del *.dvi /s
del *.blg /s
del *.thm /s
del *.toc /s
del *.out /s
del *.brf /s
del *.lof /s
del *.lot /s
del *.synctex.gz /s
del *.synctex.gz(busy) /s
del *.fdb_latexmk /s